site_name: Android ProMask
site_author: Alexis Lucien
theme: 'readthedocs'

repo_url: "https://github.com/Raidez/Android-ProMask/"

pages:
- [index.md, "Accueil"]
- [tech.md, "Documentation Technique"]
- [util.md, "Documentation Utilisateur"]
